//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImmedisTask.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImmedisTask.Data.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:6,&quot;CreatedDateTime&quot;:&quot;2020-07-25T16:16:55.353008&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-07-25T16:19:23.873356&quot;,&quot;IsActive&quot;:true,&quot;EmployeeId&quot;:9,&quot;Author&quot;:&quot;Jennifer Aniston&quot;,&quot;CommentContent&quot;:&quot;Achievement #1 unlocked&quot;}, 
        /// {&quot;Id&quot;:7,&quot;CreatedDateTime&quot;:&quot;2020-07-25T16:19:39.23558&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-07-25T16:19:46.839499&quot;,&quot;IsActive&quot;:true,&quot;EmployeeId&quot;:9,&quot;Author&quot;:&quot;Tom Cruise&quot;,&quot;CommentContent&quot;:&quot;Achievement #2 unlocked&quot;}, 
        /// {&quot;Id&quot;:5,&quot;CreatedDateTime&quot;:&quot;2020-07-25T16:15:09.382526&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-07-25T16: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:9,&quot;CreatedDateTime&quot;:&quot;2020-07-25T16:16:13.561257&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-07-25T16:17:57.337183&quot;,&quot;IsActive&quot;:true,&quot;DateJoinedCompany&quot;:&quot;2020-07-27T00:00:00&quot;,&quot;JobTitle&quot;:&quot;HR specialist&quot;,&quot;IsMonthly&quot;:true,&quot;Amount&quot;:1300.00,&quot;Department&quot;:&quot;HR&quot;,&quot;LineManagerEmployeeId&quot;:8,&quot;Address&quot;:&quot;Sofia&quot;,&quot;FirstName&quot;:&quot;Tom&quot;,&quot;LastName&quot;:&quot;Hanks&quot;}, 
        /// {&quot;Id&quot;:8,&quot;CreatedDateTime&quot;:&quot;2020-07-25T00:00:00&quot;,&quot;LastUpdatedDateTime&quot;:&quot;2020-07-25T16:18:28.505217&quot;,&quot;IsActive&quot;:true,&quot;DateJoinedCompany&quot;:&quot;2020-07-25T00:00:00&quot;,&quot;JobTitle&quot;:&quot;Developer&quot;,&quot;I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
    }
}
